workflows:
  ios_testflight:
    name: iOS TestFlight Build
    environment:
      vars:
        FLUTTER_CHANNEL: stable
        FLUTTER_VERSION: 3.35.5
        APP_STORE_CONNECT_APPLE_ID: dwscott216@gmail.com
    scripts:
      - name: Install Flutter
        script: |
          git clone https://github.com/flutter/flutter.git --branch $FLUTTER_CHANNEL --depth 1
          export PATH="$PATH:`pwd`/flutter/bin"
      - name: Flutter pub get
        script: flutter pub get
      - name: CocoaPods install
        script: |
          cd ios
          pod install
          cd ..
      - name: Build iOS IPA
        script: flutter build ipa --release
    publishing:
      app_store_connect:
        api_key: Encrypted(YOUR_API_KEY_ID_HERE)
