workflows:
  ios-release:
    name: iOS Release Build
    environment:
      groups:
        - AppStoreConnect  # contains P12_BASE64, P12_PASSWORD, PROVISIONING_PROFILE_BASE64
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        TEAM_ID: "C9M638LGTP"
        APP_STORE_APPLE_ID: "6753337719"
      xcode: latest
      cocoapods: default

    scripts:
      - name: Decode certificates and profiles
        script: |
          echo "$P12_BASE64" | base64 --decode > ios_distribution.p12
          echo "$PROVISIONING_PROFILE_BASE64" | base64 --decode > TIER.mobileprovision

          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp TIER.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/

          security create-keychain -p "" build.keychain
          security import ios_distribution.p12 -k ~/Library/Keychains/build.keychain -P "$P12_PASSWORD" -T /usr/bin/codesign || exit 1
          security list-keychains -s ~/Library/Keychains/build.keychain
          security default-keychain -s ~/Library/Keychains/build.keychain
          security unlock-keychain -p "" ~/Library/Keychains/build.keychain
          security set-key-partition-list -S apple-tool:,apple: -k "" ~/Library/Keychains/build.keychain

      - name: Install Flutter dependencies
        script: |
          flutter clean
          flutter pub get

      - name: Build archive
        script: |
          xcodebuild \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphoneos \
            -configuration Release \
            -archivePath $PWD/build/Runner.xcarchive \
            DEVELOPMENT_TEAM="$TEAM_ID" \
            CODE_SIGN_STYLE=Manual \
            clean archive | xcpretty

      - name: Export IPA
        script: |
          cat > ExportOptions.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>app-store</string>
            <key>teamID</key>
            <string>${TEAM_ID}</string>
            <key>signingStyle</key>
            <string>manual</string>
            <key>provisioningProfiles</key>
            <dict>
              <key>com.elitelywell.tier</key>
              <string>TIER</string>
            </dict>
            <key>compileBitcode</key>
            <false/>
            <key>uploadBitcode</key>
            <false/>
            <key>uploadSymbols</key>
            <true/>
          </dict>
          </plist>
          EOF

          xcodebuild -exportArchive \
            -archivePath $PWD/build/Runner.xcarchive \
            -exportPath $PWD/build/ipa \
            -exportOptionsPlist ExportOptions.plist \
            -allowProvisioningUpdates | xcpretty

    artifacts:
      - build/ipa/*.ipa

    publishing:
      app_store_connect:
        apple_id: $APP_STORE_APPLE_ID
        submit_to_testflight: true

