workflows:
  ios_only_build:
    name: iOS Only Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        XCODE_SCHEME: Runner
    scripts:
      - name: Prebuild setup
        script: |
          echo "Checking Flutter setup"
          flutter doctor -v
          echo "Precache iOS engine"
          flutter precache --ios
          echo "Get Flutter packages"
          flutter pub get
          echo "Install iOS pods"
          cd ios
          pod install --repo-update
          cd ..
      - name: Build iOS IPA
        script: |
          echo "Building iOS app"
          flutter build ipa --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
