workflows:
  ios_appstore:
    name: iOS App Store Workflow
    max_build_duration: 60
    environment:
      groups:
        - AppStoreConnect   # contains BUNDLE_ID, PRIVATE_KEY, ISSUER_ID, KEY_ID
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          echo "📦 Installing dependencies..."
          flutter pub get
          cd ios
          pod install
          cd ..
      - name: Setup automatic iOS code signing
        script: |
          #!/usr/bin/env bash
          set -e
          echo "🔐 Setting up automatic iOS code signing..."

          # Decode the base64 PRIVATE_KEY safely into a file
          echo "$PRIVATE_KEY" | base64 --decode > /tmp/AuthKey.p8

          # --- Debug output ---
          echo "🔹 First line of PEM key:"
          head -n1 /tmp/AuthKey.p8
          echo "🔹 Last line of PEM key:"
          tail -n1 /tmp/AuthKey.p8
          echo "🔹 Line count:"
          wc -l /tmp/AuthKey.p8

          # Fetch signing certificates & provisioning profiles
          app-store-connect fetch-signing-files \
            "$BUNDLE_ID" \
            --issuer-id "$ISSUER_ID" \
            --key-id "$KEY_ID" \
            --private-key "@/tmp/AuthKey.p8" \
            --type IOS_APP_STORE \
            --create
      - name: Build IPA
        script: |
          #!/usr/bin/env bash
          set -e
          echo "📦 Building iOS IPA..."
          flutter build ipa --release --no-codesign

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        api_key: $PRIVATE_KEY    # base64-encoded .p8 key
        key_id: $KEY_ID
        issuer_id: $ISSUER_ID
