workflows:
  ios_appstore:
    name: iOS App Store Workflow
    max_build_duration: 60
    environment:
      groups:
        - AppStoreConnect       # Variable group containing PRIVATE_KEY
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: "com.elitelywell.tier"
        ISSUER_ID: "d3ffa311-f124-4a74-b0ad-e4884a873c75"
        KEY_ID: "AJ2QSY34B9"
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
          cd ios
          pod install
          cd ..
      - name: Setup automatic iOS code signing
        script: |
          #!/usr/bin/env bash
          set -e
          echo "ðŸ” Setting up automatic iOS code signing..."

          # Safely write the PEM key preserving line breaks
          printf "%s\n" "$PRIVATE_KEY" > /tmp/AuthKey.p8

          # --- DEBUG: Verify formatting of private key ---
          echo "First and last lines of PEM key:"
          head -n 1 /tmp/AuthKey.p8
          tail -n 1 /tmp/AuthKey.p8

          echo "Line count of PEM key:"
          wc -l /tmp/AuthKey.p8

          echo "Showing visible whitespace for first 5 lines:"
          head -n 5 /tmp/AuthKey.p8 | cat -A

          echo "File type:"
          file /tmp/AuthKey.p8

          # Confirm BEGIN/END lines exactly match expected
          if ! head -n 1 /tmp/AuthKey.p8 | grep -q "BEGIN PRIVATE KEY"; then
            echo "ERROR: PEM key does not start with BEGIN PRIVATE KEY"
            exit 1
          fi
          if ! tail -n 1 /tmp/AuthKey.p8 | grep -q "END PRIVATE KEY"; then
            echo "ERROR: PEM key does not end with END PRIVATE KEY"
            exit 1
          fi
          echo "PEM key format looks correct âœ…"

          # Fetch and create signing certificates & provisioning profiles
          app-store-connect fetch-signing-files \
            "$BUNDLE_ID" \
            --issuer-id "$ISSUER_ID" \
            --key-id "$KEY_ID" \
            --private-key "@/tmp/AuthKey.p8" \
            --type IOS_APP_STORE \
            --create

      - name: Build iOS IPA
        script: |
          echo "ðŸ“¦ Building iOS IPA..."
          flutter build ipa --release --no-codesign

    artifacts:
      - build/ios/ipa/*.ipa
