workflows:
  ios-release:
    name: iOS App Store Build
    environment:
      flutter: stable
      xcode: 16.4
      cocoapods: default
      vars:
        BUNDLE_ID: com.elitelywell.tier
      groups:
        - AppStoreConnect
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get

      - name: Setup automatic code signing
        script: |
          #!/usr/bin/env bash
          set -e

          echo "🔐 Setting up automatic iOS code signing..."

          # Decode Base64 back into .p8 PEM file
          echo "$PRIVATE_KEY" | base64 --decode > /tmp/AuthKey.p8

          # Optional: Verify the file looks right
          echo "Checking decoded key header:"
          head -n 5 /tmp/AuthKey.p8

          echo "BUNDLE_ID: $BUNDLE_ID"
          echo "ISSUER_ID: $ISSUER_ID"
          echo "KEY_ID: $KEY_ID"

          # Fetch and create signing files automatically
          app-store-connect fetch-signing-files \
            "$BUNDLE_ID" \
            --issuer-id "$ISSUER_ID" \
            --key-id "$KEY_ID" \
            --private-key /tmp/AuthKey.p8 \
            --type IOS_APP_STORE \
            --create

      - name: Flutter build IPA
        script: |
          echo "📦 Building iOS IPA..."
          flutter build ipa --release --no-codesign

    artifacts:
      - build/ios/ipa/*.ipa
      - flutter_drive.log
