workflows:
  ios-testflight:
    name: iOS TestFlight Workflow
    environment:
      flutter: stable
      xcode: latest
      vars:
        APP_STORE_CONNECT_PRIVATE_KEY: Encrypted(...)
        APP_STORE_CONNECT_ISSUER_ID: Encrypted(...)
        APP_STORE_CONNECT_KEY_IDENTIFIER: Encrypted(...)
    scripts:
      - name: Install Flutter dependencies
        script: flutter pub get
      - name: Prepare iOS build environment
        script: |
          # Force Flutter to cache iOS artifacts
          rm -rf $FLUTTER_ROOT/bin/cache
          flutter precache --ios

          # Clean previous build artifacts
          flutter clean
          rm -rf ios/Pods ios/Podfile.lock ios/Flutter/Flutter.podspec

          # Ensure iOS deployment target >= 13
          sed -i '' "s/platform :ios, '.*'/platform :ios, '13.0'/" ios/Podfile || true

          # Update CocoaPods repo
          cd ios
          pod repo update
          pod install
          cd ..
      - name: Build iOS IPA
        script: flutter build ipa --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER

  android-release:
    name: Android Release Workflow
    environment:
      flutter: stable
    scripts:
      - name: Install Flutter dependencies
        script: flutter pub get
      - name: Build Android APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
