workflows:
  ios_testflight:
    name: iOS TestFlight Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      groups:
        - AppStoreConnect  # contains PRIVATE_KEY, KEY_ID, ISSUER_ID, APP_STORE_CONNECT_APPLE_ID
      vars:
        XCODE_SCHEME: "Runner"

    scripts:
      - name: Install dependencies
        script: |
          echo "🧹 Cleaning and getting packages..."
          flutter clean
          flutter pub get
          cd ios
          pod repo update
          pod install
          cd ..

      - name: Code signing setup
        script: |
          echo "🔐 Setting up automatic iOS code signing..."
          # The app-store-connect tool now reads credentials from env vars
          export APP_STORE_CONNECT_API_KEY_ID="$KEY_ID"
          export APP_STORE_CONNECT_API_ISSUER_ID="$ISSUER_ID"
          export APP_STORE_CONNECT_PRIVATE_KEY="$PRIVATE_KEY"
          app-store-connect fetch-signing-files \
            --type IOS_APP_STORE \
            --create

      - name: Build IPA
        script: |
          echo "📦 Building iOS IPA..."
          flutter build ipa --release

      - name: Publish to TestFlight
        script: |
          echo "🚀 Uploading to TestFlight..."
          export APP_STORE_CONNECT_API_KEY_ID="$KEY_ID"
          export APP_STORE_CONNECT_API_ISSUER_ID="$ISSUER_ID"
          export APP_STORE_CONNECT_PRIVATE_KEY="$PRIVATE_KEY"
          app-store-connect publish \
            --path build/ios/ipa/*.ipa \
            --apple-id "$APP_STORE_CONNECT_APPLE_ID" \
            --submit-to-testflight

    artifacts:
      - build/ios/ipa/*.ipa
