workflows:
  ios_testflight:
    name: iOS TestFlight Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      groups:
        - AppStoreConnect  # This is your variable group name if you use one
      vars:
        XCODE_SCHEME: "Runner"

    scripts:
      - name: Install dependencies
        script: |
          echo "🧹 Cleaning and installing dependencies..."
          flutter clean
          flutter pub get
          cd ios
          pod repo update
          pod install
          cd ..

      - name: Setup automatic code signing
        script: |
          echo "🔐 Setting up automatic iOS code signing..."

          # Decode the Base64 private key and write it to a file
          echo "$PRIVATE_KEY" | base64 --decode > /tmp/AuthKey.p8

          # Confirm environment variables are loaded (optional for debugging)
          echo "BUNDLE_ID: $BUNDLE_ID"
          echo "ISSUER_ID: $ISSUER_ID"
          echo "KEY_ID: $KEY_ID"

          # Fetch and create signing files automatically from App Store Connect
          app-store-connect fetch-signing-files \
            "$BUNDLE_ID" \
            --issuer-id "$ISSUER_ID" \
            --key-id "$KEY_ID" \
            --private-key /tmp/AuthKey.p8 \
            --type IOS_APP_STORE \
            --create

      - name: Build IPA
        script: |
          echo "📦 Building iOS IPA..."
          flutter build ipa --release --export-method app-store

      - name: Publish to TestFlight
        script: |
          echo "🚀 Uploading to TestFlight..."
          app-store-connect publish \
            --path build/ios/ipa/*.ipa \
            --api-key-id "$KEY_ID" \
            --api-issuer-id "$ISSUER_ID" \
            --api-private-key /tmp/AuthKey.p8 \
            --apple-id "$APP_STORE_CONNECT_APPLE_ID"

    artifacts:
      - build/ios/ipa/*.ipa
