workflows:
  ios_testflight:
    name: iOS TestFlight Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      groups:
        - AppStoreConnect  # contains your KEY_ID, ISSUER_ID, PRIVATE_KEY, APP_STORE_CONNECT_APPLE_ID
      vars:
        XCODE_SCHEME: "Runner"
        BUNDLE_ID: "com.elitelywell.tier"  # <-- Replace with your actual bundle ID if different

    scripts:
      - name: Install dependencies
        script: |
          echo "ðŸ§¹ Cleaning and getting packages..."
          flutter clean
          flutter pub get
          cd ios
          pod repo update
          pod install
          cd ..

      - name: Code signing setup
        script: |
          echo "ðŸ” Setting up automatic iOS code signing..."
          export APP_STORE_CONNECT_API_KEY_ID="$KEY_ID"
          export APP_STORE_CONNECT_API_ISSUER_ID="$ISSUER_ID"
          export APP_STORE_CONNECT_PRIVATE_KEY="$PRIVATE_KEY"
          app-store-connect fetch-signing-files \
            "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create

      - name: Build IPA
        script: |
          echo "ðŸ“¦ Building iOS IPA..."
          flutter build ipa --release

      - name: Publish to TestFlight
        script: |
          echo "ðŸš€ Uploading to TestFlight..."
          app-store-connect publish \
            --path build/ios/ipa/*.ipa \
            --api-key-id "$KEY_ID" \
            --api-issuer-id "$ISSUER_ID" \
            --api-private-key "$PRIVATE_KEY" \
            --apple-id "$APP_STORE_CONNECT_APPLE_ID"

    artifacts:
      - build/ios/ipa/*.ipa
