workflows:
  ios-release:
    name: iOS Release Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: 16.4
      cocoapods: 1.15.2
      vars:
        BUNDLE_ID: "com.elitelywell.tier"
        APP_NAME: "TIER Companion"
    scripts:
      - name: Install dependencies
        script: |
          flutter clean
          flutter pub get
          flutter precache --ios
          cd ios
          rm -rf Podfile.lock Pods
          pod repo update
          pod install
          cd ..

      - name: Build IPA
        script: |
          flutter build ipa --release --no-codesign

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive

    publishing:
      email:
        recipients:
          - dwscott216@gmail.com
