workflows:
  ios-release:
    name: iOS Release
    environment:
      groups:
        - AppStoreConnect
      vars:
        APP_BUNDLE_ID: "com.elitelywell.tier"
        TEAM_ID: "C9M638LGTP"
      flutter: stable
      xcode: latest

    scripts:
      - name: Install dependencies
        script: |
          flutter pub get

      - name: Decode certificates and provisioning profile
        script: |
          echo "$P12_BASE64" | base64 --decode > ios_distribution.p12
          echo "$PROVISIONING_PROFILE_BASE64" | base64 --decode > TIER.mobileprovision

          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp TIER.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/

          security create-keychain -p "" build.keychain
          security import ios_distribution.p12 -k ~/Library/Keychains/build.keychain -P "$P12_PASSWORD" -T /usr/bin/codesign
          security list-keychains -s ~/Library/Keychains/build.keychain
          security default-keychain -s ~/Library/Keychains/build.keychain
          security unlock-keychain -p "" ~/Library/Keychains/build.keychain
          security set-key-partition-list -S apple-tool:,apple: -k "" ~/Library/Keychains/build.keychain

      - name: Build iOS release IPA
        script: |
          flutter build ipa --release \
            --no-codesign

      - name: Code sign the IPA manually
        script: |
          xcodebuild -exportArchive \
            -archivePath build/ios/archive/Runner.xcarchive \
            -exportPath build/ios/ipa \
            -exportOptionsPlist ios/ExportOptions.plist \
            -allowProvisioningUpdates

    artifacts:
      - build/ios/ipa/*.ipa
