workflows:
  ios-testflight:
    name: iOS TestFlight Workflow
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Prepare Flutter and CocoaPods
        script: |
          flutter clean
          flutter pub get
          flutter precache --ios
          cd ios
          pod install --repo-update
          cd ..
      - name: Build iOS IPA
        script: |
          flutter build ipa --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        credentials: appstore_credentials

  android-release:
    name: Android Release Workflow
    environment:
      flutter: stable
    scripts:
      - name: Install dependencies
        script: |
          flutter clean
          flutter pub get
      - name: Build Android APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
