workflows:
  ios_testflight:
    name: iOS TestFlight Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      groups:
        - AppStoreConnect  # your variable group
      vars:
        XCODE_SCHEME: "Runner"
        BUNDLE_ID: "com.elitelywell.tier"

    scripts:
      - name: Install dependencies
        script: |
          echo "ðŸ§¹ Cleaning and getting packages..."
          flutter clean
          flutter pub get
          cd ios
          pod repo update
          pod install
          cd ..

      - name: Setup automatic code signing
        script: |
          #!/usr/bin/env bash
          set -e
          echo "ðŸ” Setting up automatic iOS code signing..."

          # Decode Base64 private key and fix line endings
          echo "$PRIVATE_KEY" | base64 --decode | tr -d '\r' > /tmp/AuthKey.p8
          echo "" >> /tmp/AuthKey.p8  # ensure trailing newline

          # Optional verification
          echo "Verifying private key header:"
          head -n 6 /tmp/AuthKey.p8

          echo "BUNDLE_ID: $BUNDLE_ID"
          echo "ISSUER_ID: $ISSUER_ID"
          echo "KEY_ID: $KEY_ID"

          # Fetch signing files automatically
          app-store-connect fetch-signing-files \
            "$BUNDLE_ID" \
            --issuer-id "$ISSUER_ID" \
            --key-id "$KEY_ID" \
            --private-key /tmp/AuthKey.p8 \
            --type IOS_APP_STORE \
            --create

      - name: Build IPA
        script: |
          echo "ðŸ“¦ Building iOS IPA..."
          flutter build ipa --release

      - name: Publish to TestFlight
        script: |
          echo "ðŸš€ Uploading to TestFlight..."
          app-store-connect publish \
            --path build/ios/ipa/*.ipa \
            --api-key-id "$KEY_ID" \
            --api-issuer-id "$ISSUER_ID" \
            --api-private-key "$PRIVATE_KEY" \
            --apple-id "$APP_STORE_CONNECT_APPLE_ID"

    artifacts:
      - build/ios/ipa/*.ipa
