workflows:
  ios_testflight:
    name: iOS TestFlight Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      vars:
        PRIVATE_KEY: Encrypted(...)
        KEY_ID: Encrypted(...)
        ISSUER_ID: Encrypted(...)
        APP_STORE_CONNECT_APPLE_ID: Encrypted(...)
      flutter: stable
      xcode: "16.4"
    scripts:
      - name: Install CocoaPods
        script: |
          brew install cocoapods || true
          pod install --project-directory=ios
      - name: Get dependencies
        script: flutter pub get
      - name: Build IPA
        script: flutter build ipa --release --no-codesign
      - name: Code sign IPA
        script: |
          xcrun altool --upload-app \
            --type ios \
            --file build/ios/ipa/Runner.ipa \
            --apiKey $KEY_ID \
            --apiIssuer $ISSUER_ID
