workflows:
  ios-release:
    name: iOS Manual Signing Build
    max_build_duration: 60
    instance_type: mac_mini_m1

    environment:
      flutter: stable
      xcode: latest
      vars:
        BUNDLE_ID: "com.elitelywell.tier" # <-- replace this
        CERTIFICATE_P12: Encrypted(...)       # uploaded via Codemagic UI
        CERTIFICATE_PASSWORD: Encrypted(...)  # your export password
        PROVISIONING_PROFILE_BASE64: Encrypted(...) # your .mobileprovision encoded as base64
        APP_STORE_CONNECT_APPLE_ID: "dwscott216@gmail.com"
      groups:
        - keystore_credentials

    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache

    scripts:
      - name: Install dependencies
        script: |
          flutter pub get

      - name: Decode and install signing certificate
        script: |
          echo "📦 Setting up iOS distribution certificate..."
          echo "$CERTIFICATE_P12" | base64 --decode > ios_distribution.p12
          security import ios_distribution.p12 -P "$CERTIFICATE_PASSWORD" -A
          echo "✅ Certificate imported successfully"

      - name: Decode and install provisioning profile
        script: |
          echo "📱 Installing provisioning profile..."
          echo "$PROVISIONING_PROFILE_BASE64" | base64 --decode > provisioning.mobileprovision
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          PROFILE_UUID=$(grep -a -o '<key>UUID</key><string>.*</string>' provisioning.mobileprovision | head -1 | sed -E 's/.*<string>(.*)<\/string>.*/\1/')
          cp provisioning.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/$PROFILE_UUID.mobileprovision
          echo "✅ Provisioning profile installed: $PROFILE_UUID"

      - name: Build iOS IPA
        script: |
          echo "🏗️ Building iOS IPA..."
          flutter build ipa --release --no-codesign
          echo "✅ Flutter build completed"

    artifacts:
      - build/**/outputs/**/*.ipa
      - build/ios/ipa/*.ipa
      - flutter_drive.log

    publishing:
      email:
        recipients:
          - dwscott216@gmail.com
