workflows:
  ios-manual-signing:
    name: iOS Manual Signing
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      vars:
        P12_PASSWORD: Encrypted(...)
        P12_BASE64: Encrypted(...)
        PROVISIONING_PROFILE_BASE64: Encrypted(...)
        BUNDLE_ID: com.elitelywell.tier
        TEAM_ID: C9M638LGTP   # <-- your Apple Team ID here
    scripts:
      - name: Decode provisioning profile
        script: |
          echo $PROVISIONING_PROFILE_BASE64 | base64 --decode > /tmp/TIER.mobileprovision
          echo $P12_BASE64 | base64 --decode > /tmp/ios_distribution.p12
      - name: Install Flutter dependencies
        script: |
          flutter pub get
          flutter precache
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod repo update
          pod install
          cd ..
      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign
          xcodebuild -workspace ios/Runner.xcworkspace \
                     -scheme Runner \
                     -configuration Release \
                     -archivePath $CM_BUILD_DIR/build/Runner.xcarchive \
                     CODE_SIGN_STYLE=Manual \
                     DEVELOPMENT_TEAM=$TEAM_ID \
                     PROVISIONING_PROFILE_SPECIFIER=TIER \
                     PRODUCT_BUNDLE_IDENTIFIER=$BUNDLE_ID \
                     clean archive
    artifacts:
      - build/ios/Runner.xcarchive
