workflows:
  ios_appstore:
    name: iOS App Store Workflow
    max_build_duration: 60

    environment:
      # Import your secure variables from this group in Codemagic UI:
      groups:
        - AppStoreConnect    # must include PRIVATE_KEY, KEY_ID, ISSUER_ID, BUNDLE_ID, APP_STORE_CONNECT_APPLE_ID
      flutter: stable
      xcode: latest
      cocoapods: default

    scripts:
      - name: Install dependencies
        script: |
          echo "📦 Installing dependencies..."
          flutter pub get
          cd ios || exit 1
          pod install --repo-update || true
          cd ..

      - name: Setup automatic iOS code signing
        script: |
          #!/usr/bin/env bash
          set -euo pipefail
          echo "🔐 Setting up automatic iOS code signing..."

          # Ensure required env vars are present (fail early if not)
          : "${PRIVATE_KEY:?PRIVATE_KEY is not set in environment/group}"
          : "${KEY_ID:?KEY_ID is not set in environment/group}"
          : "${ISSUER_ID:?ISSUER_ID is not set in environment/group}"
          : "${BUNDLE_ID:?BUNDLE_ID is not set in environment/group}"

          # Decode base64 key safely and clean it (no duplicates, no CRLF)
          printf "%s" "$PRIVATE_KEY" | base64 --decode | awk '!seen[$0]++' | sed 's/\r$//' > /tmp/AuthKey.p8
          echo "✅ /tmp/AuthKey.p8 created"

          # Debug sanity checks
          echo "----- FILE CHECK (first/last 6 lines) -----"
          head -n6 /tmp/AuthKey.p8 || true
          echo "..."
          tail -n6 /tmp/AuthKey.p8 || true
          echo "File size (bytes): $(wc -c < /tmp/AuthKey.p8)"
          echo "-------------------------------------------"

          # Validate PEM format (BEGIN/END must exist and only once)
          if ! grep -q "^-----BEGIN PRIVATE KEY-----" /tmp/AuthKey.p8; then
            echo "❌ ERROR: PEM key does not contain BEGIN PRIVATE KEY"
            exit 1
          fi
          if ! grep -q "^-----END PRIVATE KEY-----" /tmp/AuthKey.p8; then
            echo "❌ ERROR: PEM key does not contain END PRIVATE KEY"
            exit 1
          fi

          # Keep only the first PEM block (in case of accidental duplication)
          awk '/-----BEGIN PRIVATE KEY-----/{p=1} p{print} /-----END PRIVATE KEY-----/{p=0; exit}' /tmp/AuthKey.p8 > /tmp/AuthKey_clean.p8
          mv /tmp/AuthKey_clean.p8 /tmp/AuthKey.p8
          sed -i '' -e 's/\r$//' /tmp/AuthKey.p8 2>/dev/null || sed -i -e 's/\r$//' /tmp/AuthKey.p8 2>/dev/null || true

          echo "✅ Final PEM content:"
          sed -n '1,10p' /tmp/AuthKey.p8
          echo "..."
          sed -n ':a;N;$!ba;s/\n/\\n/g;p' /tmp/AuthKey.p8 >/dev/null 2>&1 || true
          echo "✅ PEM ready for signing"

          # Optional: test parsing with OpenSSL (if available)
          if command -v openssl >/dev/null 2>&1; then
            if openssl pkcs8 -in /tmp/AuthKey.p8 -nocrypt -inform PEM -out /dev/null 2>/dev/null; then
              echo "✅ OpenSSL parsed key OK"
            else
              echo "❌ OpenSSL failed to parse key (will still try app-store-connect CLI)"
            fi
          fi

          # Fetch signing certificates/profiles from App Store Connect
          app-store-connect fetch-signing-files \
            "$BUNDLE_ID" \
            --issuer-id "$ISSUER_ID" \
            --key-id "$KEY_ID" \
            --private-key /tmp/AuthKey.p8 \
            --type IOS_APP_STORE \
            --create

      - name: Build signed iOS IPA
        script: |
          # Build signed IPA: Flutter + Xcode will use the downloaded profiles/certs
          echo "🚀 Building iOS IPA..."
          flutter build ipa --release

      - name: Publish to App Store Connect (TestFlight)
        script: |
          echo "📤 Uploading signed IPA to TestFlight (app-store-connect CLI)..."
          # app-store-connect publish accepts a path; use wildcard or explicit file
          app-store-connect publish \
            --path "build/ios/ipa/*.ipa" \
            --issuer-id "$ISSUER_ID" \
            --key-id "$KEY_ID" \
            --private-key /tmp/AuthKey.p8

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/AuthKey.p8
