workflows:
  ios-manual-signing:
    name: iOS Manual Signing
    environment:
      vars:
        BUNDLE_ID: "com.elitelywell.tier"
        P12_PASSWORD: Encrypted  # set in Codemagic env vars
        # P12_BASE64 and PROVISIONING_PROFILE_BASE64 are also set in Codemagic env vars
      xcode: latest
      cocoapods: default
      flutter: stable
    scripts:
      - name: Decode .p12 and .mobileprovision from env
        script: |
          echo "📦 Decoding certificates and provisioning profiles..."
          echo "$P12_BASE64" | base64 --decode > ios_distribution.p12
          echo "$PROVISIONING_PROFILE_BASE64" | base64 --decode > TIER.mobileprovision
      - name: Setup manual signing
        script: |
          echo "🔐 Installing certificate and provisioning profile..."
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp TIER.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/
          security create-keychain -p "" build.keychain
          security import ios_distribution.p12 -k ~/Library/Keychains/build.keychain -P "$P12_PASSWORD" -T /usr/bin/codesign
          security list-keychains -s ~/Library/Keychains/build.keychain
          security unlock-keychain -p "" ~/Library/Keychains/build.keychain
      - name: Install dependencies
        script: |
          flutter pub get
          pod install --project-directory=ios
      - name: Build iOS app
        script: |
          flutter build ipa --release --export-options-plist ios/ExportOptions.plist
    artifacts:
      - build/ios/ipa/*.ipa
