workflows:
  ios_appstore:
    name: iOS App Store Workflow
    max_build_duration: 60
    environment:
      groups:
        - AppStoreConnect   # contains BUNDLE_ID, PRIVATE_KEY (base64), ISSUER_ID, KEY_ID
      flutter: stable
      xcode: latest
      cocoapods: default

    scripts:
      - name: Install dependencies
        script: |
          echo "📦 Installing dependencies..."
          flutter pub get
          cd ios
          pod install
          cd ..

      - name: Setup automatic iOS code signing
        script: |
          #!/usr/bin/env bash
          set -e
          echo "🔐 Setting up automatic iOS code signing..."

          echo "🔹 Decoding PRIVATE_KEY into /tmp/AuthKey.p8"
          echo "$PRIVATE_KEY" | base64 --decode > /tmp/AuthKey.p8

          echo "🔹 Debug info for PEM key:"
          echo "Full content of PEM key:"
          cat /tmp/AuthKey.p8
          echo "First line:"
          head -n1 /tmp/AuthKey.p8
          echo "Second line:"
          head -n2 /tmp/AuthKey.p8 | tail -n1
          echo "Third line:"
          head -n3 /tmp/AuthKey.p8 | tail -n1
          echo "Last 3 lines:"
          tail -n3 /tmp/AuthKey.p8
          echo "Line count:"
          wc -l /tmp/AuthKey.p8
          echo "Show visible whitespace for all lines:"
          cat -n /tmp/AuthKey.p8 | sed -n l
          echo "Hex dump of entire key:"
          hexdump -C /tmp/AuthKey.p8

          echo "BUNDLE_ID: $BUNDLE_ID"
          echo "ISSUER_ID: $ISSUER_ID"
          echo "KEY_ID: $KEY_ID"

          # Validate BEGIN/END lines
          if ! head -n1 /tmp/AuthKey.p8 | grep -q "BEGIN PRIVATE KEY"; then
            echo "ERROR: PEM key does not start with BEGIN PRIVATE KEY"
            exit 1
          fi
          if ! tail -n1 /tmp/AuthKey.p8 | grep -q "END PRIVATE KEY"; then
            echo "ERROR: PEM key does not end with END PRIVATE KEY"
            exit 1
          fi
          echo "PEM key format looks correct ✅"

          echo "🔹 Running app-store-connect fetch-signing-files"
          app-store-connect fetch-signing-files \
            "$BUNDLE_ID" \
            --issuer-id "$ISSUER_ID" \
            --key-id "$KEY_ID" \
            --private-key "@/tmp/AuthKey.p8" \
            --type IOS_APP_STORE \
            --create

      - name: Build IPA
        script: |
          #!/usr/bin/env bash
          set -e
          echo "📦 Building iOS IPA..."
          flutter build ipa --release --no-codesign

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        api_key: $PRIVATE_KEY
        key_id: $KEY_ID
        issuer_id: $ISSUER_ID
