workflows:
  ios-release:
    name: iOS Release Build
    environment:
      flutter: stable
      xcode: 16.4
      vars:
        BUNDLE_ID: "com.elitelywell.tier"
        ISSUER_ID: "d3ffa311-f124-4a74-b0ad-e4884a873c75"
        KEY_ID: "AJ2QSY34B9"
      groups:
        # 👇 Create this group in Codemagic UI and add:
        # PRIVATE_KEY (App Store Connect .p8 contents)
        - app_store_connect_credentials

    scripts:
      - name: 🔐 Setup automatic iOS code signing
        script: |
          #!/usr/bin/env bash
          set -e
          echo "🔐 Setting up automatic iOS code signing..."

          # Safely write the PEM key to disk
          echo "$PRIVATE_KEY" | awk '{printf "%s\n", $0}' > /tmp/AuthKey.p8

          echo "Verifying private key header:"
          head -n 6 /tmp/AuthKey.p8
          echo "File type:"
          file /tmp/AuthKey.p8
          echo "BUNDLE_ID: $BUNDLE_ID"
          echo "ISSUER_ID: $ISSUER_ID"
          echo "KEY_ID: $KEY_ID"

          # Fetch signing certificates and provisioning profiles
          app-store-connect fetch-signing-files \
            "$BUNDLE_ID" \
            --issuer-id "$ISSUER_ID" \
            --key-id "$KEY_ID" \
            --private-key "@/tmp/AuthKey.p8" \
            --type IOS_APP_STORE \
            --create

      - name: 🧱 Build iOS release IPA
        script: |
          flutter clean
          flutter pub get
          flutter build ipa --release --no-codesign

      - name: 📦 Export signed IPA
        script: |
          xcode-project build-ipa \
            --workspace ios/Runner.xcworkspace \
            --scheme Runner \
            --export-method app-store

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/ipa/*.app
      - /tmp/xcodebuild_logs/*.log

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false

    integrations:
      app_store_connect: Codemagic App Store Connect

