workflows:
  ios-testflight:
    name: iOS TestFlight Build
    environment:
      groups:
        - appstore_credentials
      flutter: stable
      xcode: 16.4
      cocoapods: 1.16.2
    scripts:
      - name: Clean Flutter and Pod cache
        script: |
          flutter clean
          flutter pub get
          rm -rf ios/Pods ios/Podfile.lock
          pod repo update
      - name: Build iOS IPA
        script: |
          flutter build ipa --release \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        key_identifier: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        private_key: $APP_STORE_CONNECT_PRIVATE_KEY
        submit_to_testflight: true
