workflows:
  ios-release:
    name: iOS Release Build
    environment:
      groups:
        - AppStoreConnect # this matches your Codemagic variable group name
      vars:
        BUNDLE_ID: "com.elitelywell.tier"
        ISSUER_ID: "d3ffa311-f124-4a74-b0ad-e4884a873c75"
        KEY_ID: "AJ2QSY34B9"
      xcode: latest
    integrations:
      app_store_connect: TIER
    scripts:
      - name: Setup automatic code signing
        script: |
          #!/usr/bin/env bash
          set -e
          echo "ðŸ” Setting up automatic iOS code signing..."

          # Safely write the PEM key, preserving line breaks and removing carriage returns
          printf "%s" "$PRIVATE_KEY" | tr -d '\r' > /tmp/AuthKey.p8

          echo "Verifying private key header:"
          head -n 6 /tmp/AuthKey.p8
          echo "File type:"
          file /tmp/AuthKey.p8
          echo "BUNDLE_ID: $BUNDLE_ID"
          echo "ISSUER_ID: $ISSUER_ID"
          echo "KEY_ID: $KEY_ID"

          app-store-connect fetch-signing-files \
            "$BUNDLE_ID" \
            --issuer-id "$ISSUER_ID" \
            --key-id "$KEY_ID" \
            --private-key "@/tmp/AuthKey.p8" \
            --type IOS_APP_STORE \
            --create
      - name: Build IPA
        script: |
          flutter build ipa --release --no-codesign
      - name: Export IPA
        script: |
          xcode-project build-ipa --workspace ios/Runner.xcworkspace --scheme Runner --export-method app-store
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_app_store: true

