workflows:
  ios-testflight:
    name: iOS TestFlight Workflow
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Prepare iOS build environment
        script: |
          flutter clean
          flutter pub get
          flutter precache --ios
          rm -rf ios/Pods ios/Podfile.lock ios/Flutter/Flutter.podspec
          sed -i '' "s/platform :ios, '.*'/platform :ios, '13.0'/" ios/Podfile || true
      - name: Install Pods
        script: |
          cd ios
          pod install --repo-update
          cd ..
      - name: Build iOS IPA
        script: flutter build ipa --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER

  android-release:
    name: Android Release Workflow
    environment:
      flutter: stable
    scripts:
      - name: Install Flutter dependencies
        script: flutter pub get
      - name: Build Android APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk


