workflows:
  ios-release:
    name: iOS Release Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: 16.4
      vars:
        BUNDLE_ID: "com.elitelywell.tier"
        ISSUER_ID: "d3ffa311-f124-4a74-b0ad-e4884a873c75"
        KEY_ID: "AJ2QSY34B9"
      groups:
        - app_store_connect_credentials  # contains PRIVATE_KEY

    scripts:
      - name: ðŸ” Setup automatic iOS code signing
        script: |
          #!/usr/bin/env bash
          set -e
          echo "ðŸ” Setting up automatic iOS code signing..."

          # Write the PEM key safely
          printf "%s" "$PRIVATE_KEY" | tr -d '\r' > /tmp/AuthKey.p8

          echo "Verifying private key header:"
          head -n 6 /tmp/AuthKey.p8
          echo "File type:"
          file /tmp/AuthKey.p8
          echo "BUNDLE_ID: $BUNDLE_ID"
          echo "ISSUER_ID: $ISSUER_ID"
          echo "KEY_ID: $KEY_ID"

          # Fetch certificates and provisioning profiles from App Store Connect
          app-store-connect fetch-signing-files \
            "$BUNDLE_ID" \
            --issuer-id "$ISSUER_ID" \
            --key-id "$KEY_ID" \
            --private-key "@/tmp/AuthKey.p8" \
            --type IOS_APP_STORE \
            --create

      - name: ðŸ§± Build release IPA
        script: |
          flutter clean
          flutter pub get
          flutter build ipa --release --no-codesign

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/ipa/*.app
