workflows:
  ios-release:
    name: iOS Release Build
    environment:
      groups:
        - appstore_credentials    # must contain PRIVATE_KEY, ISSUER_ID, KEY_ID
      vars:
        BUNDLE_ID: "com.yourcompany.yourapp"
    scripts:
      - name: Setup automatic iOS code signing
        script: |
          #!/usr/bin/env bash
          set -e
          echo "🔐 Setting up automatic iOS code signing..."

          # Decode your base64 key into a PEM
          printf "%s" "$PRIVATE_KEY" | base64 --decode > /tmp/AuthKey.p8
          echo "✅ AuthKey.p8 created at /tmp/AuthKey.p8"

          head -n2 /tmp/AuthKey.p8
          tail -n2 /tmp/AuthKey.p8
          wc -l /tmp/AuthKey.p8

          if ! grep -q "BEGIN PRIVATE KEY" /tmp/AuthKey.p8; then
            echo "❌ Invalid PEM key"
            exit 1
          fi
          echo "✅ PEM structure good"

          app-store-connect fetch-signing-files \
            "$BUNDLE_ID" \
            --issuer-id "$ISSUER_ID" \
            --key-id "$KEY_ID" \
            --private-key /tmp/AuthKey.p8 \
            --type IOS_APP_STORE \
            --create

      - name: Flutter clean and build
        script: |
          flutter clean
          flutter pub get
          flutter build ipa --release --no-codesign

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/ipa/*.dSYM.zip

    publishing:
      app_store_connect:
        api_key:
          private_key: $PRIVATE_KEY
          key_id: $KEY_ID
          issuer_id: $ISSUER_ID
