workflows:
  ios_appstore:
    name: iOS App Store Workflow
    max_build_duration: 60
    environment:
      groups:
        - AppStoreConnect       # Must contain PRIVATE_KEY variable (multi-line)
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: "com.elitelywell.tier"
        ISSUER_ID: "d3ffa311-f124-4a74-b0ad-e4884a873c75"
        KEY_ID: "AJ2QSY34B9"
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
          cd ios
          pod install
          cd ..
      - name: Setup automatic iOS code signing
        script: |
          #!/usr/bin/env bash
          set -e
          echo "ðŸ” Setting up automatic iOS code signing..."

          # Normalize line endings and remove trailing whitespace
          echo "$PRIVATE_KEY" | sed 's/\r$//' | sed 's/[[:space:]]*$//' > /tmp/AuthKey.p8

          # --- DEBUG INFORMATION ---
          echo "ðŸ”¹ First 3 lines of PEM key:"
          head -n 3 /tmp/AuthKey.p8
          echo "ðŸ”¹ Last 3 lines of PEM key:"
          tail -n 3 /tmp/AuthKey.p8
          echo "ðŸ”¹ Full line count:"
          wc -l /tmp/AuthKey.p8
          echo "ðŸ”¹ File type:"
          file /tmp/AuthKey.p8
          echo "ðŸ”¹ Show visible whitespace for first 5 lines:"
          head -n 5 /tmp/AuthKey.p8 | sed -n l
          echo "ðŸ”¹ Hex dump of first 3 lines:"
          head -n 3 /tmp/AuthKey.p8 | hexdump -C
          echo "BUNDLE_ID: $BUNDLE_ID"
          echo "ISSUER_ID: $ISSUER_ID"
          echo "KEY_ID: $KEY_ID"

          # Validate BEGIN/END lines
          if ! head -n1 /tmp/AuthKey.p8 | grep -q "BEGIN PRIVATE KEY"; then
            echo "ERROR: PEM key does not start with BEGIN PRIVATE KEY"
            exit 1
          fi
          if ! tail -n1 /tmp/AuthKey.p8 | grep -q "END PRIVATE KEY"; then
            echo "ERROR: PEM key does not end with END PRIVATE KEY"
            exit 1
          fi
          echo "PEM key format looks correct âœ…"

          # Fetch signing certificates & provisioning profiles
          app-store-connect fetch-signing-files \
            "$BUNDLE_ID" \
            --issuer-id "$ISSUER_ID" \
            --key-id "$KEY_ID" \
            --private-key "@/tmp/AuthKey.p8" \
            --type IOS_APP_STORE \
            --create

      - name: Build iOS IPA
        script: |
          echo "ðŸ“¦ Building iOS IPA..."
          flutter build ipa --release --no-codesign

    artifacts:
      - build/ios/ipa/*.ipa
