workflows:
  ios_testflight:
    name: iOS TestFlight Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      groups:
        - AppStoreConnect  # group contains PRIVATE_KEY, KEY_ID, ISSUER_ID, APP_STORE_CONNECT_APPLE_ID
      vars:
        XCODE_SCHEME: "Runner"

    scripts:
      - name: Install dependencies
        script: |
          echo "🧹 Cleaning and getting packages..."
          flutter clean
          flutter pub get
          cd ios
          pod repo update
          pod install
          cd ..

      - name: Code signing setup
        script: |
          echo "🔐 Setting up automatic iOS code signing..."
          app-store-connect fetch-signing-files \
            --api-key-id "$KEY_ID" \
            --api-issuer-id "$ISSUER_ID" \
            --api-private-key "$PRIVATE_KEY" \
            --type IOS_APP_STORE \
            --create

      - name: Build IPA
        script: |
          echo "📦 Building iOS IPA..."
          flutter build ipa --release

      - name: Publish to TestFlight
        script: |
          echo "🚀 Uploading to TestFlight..."
          app-store-connect publish \
            --path build/ios/ipa/*.ipa \
            --api-key-id "$KEY_ID" \
            --api-issuer-id "$ISSUER_ID" \
            --api-private-key "$PRIVATE_KEY" \
            --apple-id "$APP_STORE_CONNECT_APPLE_ID"

    artifacts:
      - build/ios/ipa/*.ipa
