workflows:
  ios-testflight:
    name: iOS TestFlight Workflow
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Install Flutter dependencies
        script: flutter pub get
      - name: Build iOS IPA
        script: |
          # Ensure iOS deployment target >=13
          sed -i '' "s/platform :ios, '.*'/platform :ios, '13.0'/" ios/Podfile || true
          flutter build ipa --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER

  android-release:
    name: Android Release Workflow
    environment:
      flutter: stable
    scripts:
      - name: Install Flutter dependencies
        script: flutter pub get
      - name: Build Android APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
