workflows:
  ios_testflight:
    name: iOS TestFlight Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      groups:
        - AppStoreConnect  # make sure this group includes KEY_ID, ISSUER_ID, PRIVATE_KEY, APP_STORE_CONNECT_APPLE_ID
      vars:
        XCODE_SCHEME: "Runner"
        BUNDLE_ID: "com.elitelywell.tier"

    scripts:
      - name: Install dependencies
        script: |
          echo "ðŸ§¹ Cleaning and installing pods..."
          flutter clean
          flutter pub get
          cd ios
          pod repo update
          pod install
          cd ..

      - name: Code signing setup
        script: |
          echo "ðŸ” Setting up automatic iOS code signing..."
          echo "$PRIVATE_KEY" > /tmp/AuthKey.p8
          app-store-connect fetch-signing-files \
            "$BUNDLE_ID" \
            --issuer-id "$ISSUER_ID" \
            --key-id "$KEY_ID" \
            --private-key /tmp/AuthKey.p8 \
            --type IOS_APP_STORE \
            --create

          echo "âœ… Signing files fetched successfully."

      - name: Build IPA
        script: |
          echo "ðŸ“¦ Building iOS IPA..."
          flutter build ipa --release --no-codesign

      - name: Publish to TestFlight
        script: |
          echo "ðŸš€ Uploading to TestFlight..."
          app-store-connect publish \
            --path build/ios/ipa/*.ipa \
            --issuer-id "$ISSUER_ID" \
            --key-id "$KEY_ID" \
            --private-key /tmp/AuthKey.p8 \
            --apple-id "$APP_STORE_CONNECT_APPLE_ID"

    artifacts:
      - build/ios/ipa/*.ipa
