workflows:
  ios_testflight:
    name: iOS TestFlight Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      vars:
        XCODE_SCHEME: "Runner"

    scripts:
      - name: Install dependencies
        script: |
          echo "ðŸ§¹ Cleaning and getting packages..."
          flutter clean
          flutter pub get
          cd ios
          pod repo update
          pod install
          cd ..

      - name: Setup automatic code signing
        script: |
          echo "ðŸ” Setting up automatic iOS code signing..."
          echo "$PRIVATE_KEY" | base64 --decode > /tmp/AuthKey.p8
          app-store-connect fetch-signing-files \
            "$BUNDLE_ID" \
            --issuer-id "$ISSUER_ID" \
            --key-id "$KEY_ID" \
            --private-key /tmp/AuthKey.p8 \
            --type IOS_APP_STORE \
            --create

      - name: Build IPA
        script: |
          echo "ðŸ“¦ Building iOS IPA..."
          flutter build ipa --release

      - name: Publish to TestFlight
        script: |
          echo "ðŸš€ Uploading to TestFlight..."
          app-store-connect publish \
            --path build/ios/ipa/*.ipa \
            --api-key-id "$KEY_ID" \
            --api-issuer-id "$ISSUER_ID" \
            --api-private-key /tmp/AuthKey.p8 \
            --apple-id "$APP_STORE_CONNECT_APPLE_ID"

    artifacts:
      - build/ios/ipa/*.ipa


