workflows:
  ios_only_build:
    name: iOS Only Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        XCODE_SCHEME: Runner
    scripts:
      - name: Prebuild setup
        script: |
          echo "=== Flutter doctor ==="
          flutter doctor -v
          echo "=== Flutter clean ==="
          flutter clean
          echo "=== Get Flutter packages ==="
          flutter pub get
          echo "=== Precache iOS engine ==="
          flutter precache --ios
          
          echo "=== Check podhelper.rb exists ==="
          if [ ! -f ios/.ios/Flutter/podhelper.rb ]; then
            echo "⚠️ podhelper.rb not found, forcing flutter pub get and precache again"
            flutter pub get
            flutter precache --ios
          fi
          
          echo "=== Install iOS pods ==="
          cd ios
          pod cache clean --all
          pod repo update
          pod install --verbose || pod install --verbose
          cd ..
          
      - name: Build iOS IPA (Verbose)
        script: |
          echo "=== Building iOS app IPA ==="
          flutter build ipa --release --no-codesign -v

    artifacts:
      - build/ios/ipa/*.ipa
