workflows:
  ios_appstore:
    name: iOS App Store Workflow
    max_build_duration: 60
    environment:
      groups:
        - AppStoreConnect
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
          cd ios
          pod install
          cd ..
      - name: Setup automatic code signing
        script: |
          #!/usr/bin/env bash
          set -e
          echo "🔐 Setting up automatic iOS code signing..."

          # Decode Base64 private key correctly
          echo "$PRIVATE_KEY" | base64 --decode > /tmp/AuthKey.p8
          echo "" >> /tmp/AuthKey.p8  # ensure newline at end

          # Optional verification
          echo "Verifying private key header:"
          head -n 6 /tmp/AuthKey.p8

          echo "BUNDLE_ID: $BUNDLE_ID"
          echo "ISSUER_ID: $ISSUER_ID"
          echo "KEY_ID: $KEY_ID"

          # Fetch signing files automatically
          app-store-connect fetch-signing-files \
            "$BUNDLE_ID" \
            --issuer-id "$ISSUER_ID" \
            --key-id "$KEY_ID" \
            --private-key /tmp/AuthKey.p8 \
            --type IOS_APP_STORE \
            --create
      - name: Build IPA
        script: |
          flutter build ipa --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
