workflows:
  ios-release:
    name: iOS Release Build
    environment:
      vars:
        BUNDLE_ID: "com.elitelywell.tier"
        TEAM_ID: "C9M638LGTP" # from developer.apple.com/account
      flutter: stable
      xcode: latest
    scripts:
      - name: Decode certificates and profiles
        script: |
          echo "$P12_BASE64" | base64 --decode > ios_distribution.p12
          echo "$PROVISIONING_PROFILE_BASE64" | base64 --decode > TIER.mobileprovision

          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp TIER.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/

          security create-keychain -p "" build.keychain
          security import ios_distribution.p12 -k ~/Library/Keychains/build.keychain -P "$P12_PASSWORD" -T /usr/bin/codesign
          security list-keychains -s ~/Library/Keychains/build.keychain
          security default-keychain -s ~/Library/Keychains/build.keychain
          security unlock-keychain -p "" ~/Library/Keychains/build.keychain
          security set-key-partition-list -S apple-tool:,apple: -k "" ~/Library/Keychains/build.keychain

      - name: Get dependencies
        script: |
          flutter pub get
          cd ios
          rm -rf Pods Podfile.lock
          pod install --repo-update
          cd ..

      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign
          xcodebuild -workspace ios/Runner.xcworkspace \
                     -scheme Runner \
                     -configuration Release \
                     -archivePath $CM_BUILD_DIR/build/Runner.xcarchive \
                     DEVELOPMENT_TEAM=$TEAM_ID \
                     PROVISIONING_PROFILE_SPECIFIER=TIER \
                     PRODUCT_BUNDLE_IDENTIFIER=$BUNDLE_ID \
                     CODE_SIGN_STYLE=Manual \
                     clean archive
