
name: tier_companion
description: Elitelywell's TIER brought to the appstore.
publish_to: 'none'
version: 1.0.0+2   # 1.0.0 is CFBundleShortVersionString, +1 is CFBundleVersion

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.3
  intl: ^0.20.2
  uuid: ^4.3.3
  http: ^1.5.0
  url_launcher: ^6.3.0
  change_app_package_name: ^1.5.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/lotus_transparent.png"       # your lotus-only version
  adaptive_icon_background: "#EAF6F6" # soft background from logo
  adaptive_icon_foreground: "assets/lotus_transparent.png"

flutter_native_splash:
  color: "#EAF6F6"                # background color
  image: "assets/lotus_transparent.png"          # your logo file

flutter:
  uses-material-design: true
