name: tier_flutter
description: A new Flutter project.
publish_to: "none" # This prevents publishing to pub.dev

version: 1.0.0+5

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Core Flutter packages
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  url_launcher: ^6.3.1
  http: ^1.2.2
  shared_preferences: ^2.3.1
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/

  # Example: fonts (optional)
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: fonts/Roboto-Regular.ttf
  #       - asset: fonts/Roboto-Bold.ttf
  #         weight: 700
