name: tier_flutter
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+5

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  url_launcher: ^6.3.0
  http: ^1.2.2
  shared_preferences: ^2.3.1
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  # If you have assets, keep them here
  assets:
    - assets/
