# Uncomment this line to define a global platform for your project
platform :ios, '12.0'

use_frameworks!
use_modular_headers!

# Flutter root path
flutter_application_path = '../'

# Load Flutter's podhelper
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'Runner' do
  flutter_ios_podfile_setup

  use_frameworks!
  use_modular_headers!

  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
